(
 ("default" . ((user-emacs-directory . "~/.emacs.d/")
               (env . (("SPACEMACSDIR" . "~/.spacemacs.d/")))
               )
  )
 ("dev" . ((user-emacs-directory . "~/.chemacs/Spacemacs/Dev/.emacs.d/")
           (env . (("SPACEMACSDIR" . "~/.chemacs/Spacemacs/Dev/.spacemacs.d/")))
           (server-name . "Spacemacs-Dev")
           )
  )
 ("vanilla" . ((user-emacs-directory . "~/.chemacs/Vanilla/Dev/.emacs.d/")
               (server-name . "Vanilla-Dev")
               )
  )
 )
